### ISSUE TITLE
Issue with writing output

### ISSUE THREAD

**Issue by vbaldassare** [GabrielaCR/AGNfitter#17]
Hello- I am running the example code, and am having an issue with the code output. It writes files "samples_mcmc.sav" and "samples_burn1-2-3.sav", and there is a file called "traces_mcmc.pdf" that I cannot open. The terminal output (before and including the error) is below. Any advice you have would be appreciated! Thanks!

Running MCMC with 10000 steps
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
3.6 min elapsed
_________________________________
Properties of the sampling results:
- Mean acceptance fraction 0.12125699999999999
- Mean autocorrelation time 496.05364887436644
Traceback (most recent call last):
  File "./RUN_AGNfitter_multi.py", line 264, in <module>
    RUN_AGNfitter_multiprocessing(args.ncpu, data_ALL, Modelsdict)
  File "./RUN_AGNfitter_multi.py", line 203, in RUN_AGNfitter_multiprocessing
    catalog_fitting = pool.map(multi_run_wrapper, itertools.izip(range(nsources), itertools.repeat(data_obj), itertools.repeat(modelsdict)))
  File "/Users/vbaldassare/anaconda2/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Users/vbaldassare/anaconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
RuntimeError: latex was not able to process the following string:
'lp'

Here is the full report generated by latex:
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/MacPorts 2018.47642_8) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/Users/vbaldassare/.matplotlib/tex.cache/3bbc0f8d536770a62891b7cc8788c317.tex
LaTeX2e <2017-04-15>
Babel <3.10> and hyphenation patterns for 46 language(s) loaded.
(/opt/local/share/texmf-texlive/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/opt/local/share/texmf-texlive/tex/latex/base/size10.clo))

! LaTeX Error: File `type1cm.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.4 ^^M
       
No pages of output.
Transcript written on 3bbc0f8d536770a62891b7cc8788c317.log.

**Comment by GabrielaCR** [comment]
Hi! This appears to be a LateX error, can other python scripts in your computer use latex for plotting normally? I would suggest to run the code in independent version without multiprocessing (just adding a -i, see Wiki) to see which specific line is causing the problem.

**Comment by mothog** [comment]
Hi, I'm trying to run an example code and I get this:

Traceback (most recent call last):
  File "/idia/users/thando/AGNfitter/RUN_AGNfitter_multi.py", line 258, in <module>
    Modelsdict = MAKE_model_dictionary(cat, filters, clobbermodel=clobbermodel)
  File "/idia/users/thando/AGNfitter/RUN_AGNfitter_multi.py", line 83, in MAKE_model_dictionary
    MODELFILES.construct(cat['path'])
  File "/idia/users/thando/AGNfitter/functions/CONSTRUCT_modelobjects.py", line 182, in construct
    SB.build()
  File "/idia/users/thando/AGNfitter/functions/CONSTRUCT_modelobjects.py", line 140, in build
    irlum,sb_wave, sb_SED = npzfile['arr_0'], npzfile['arr_1'], npzfile['arr_2']
  File "/users/thando/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/users/thando/.local/lib/python2.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
