### ISSUE TITLE
Problem in running the example after installation

### ISSUE THREAD

**Issue by irhamta** [GabrielaCR/AGNfitter#18]
Hi, 
I'm just installed the AGNfitter and try to run the example code by following the readme. However, I got this error:

```
Traceback (most recent call last):
  File "./RUN_AGNfitter_multi.py", line 258, in <module>
    Modelsdict = MAKE_model_dictionary(cat, filters, clobbermodel=clobbermodel)
  File "./RUN_AGNfitter_multi.py", line 83, in MAKE_model_dictionary
    MODELFILES.construct(cat['path'])
  File "/home/irhamta/Documents/Research/Finding_Quasar/Software/AGNfitter/functions/CONSTRUCT_modelobjects.py", line 182, in construct
    SB.build()
  File "/home/irhamta/Documents/Research/Finding_Quasar/Software/AGNfitter/functions/CONSTRUCT_modelobjects.py", line 140, in build
    irlum,sb_wave, sb_SED = npzfile['arr_0'], npzfile['arr_1'], npzfile['arr_2']
  File "/home/irhamta/anaconda3/envs/agnfit/lib/python2.7/site-packages/numpy/lib/npyio.py", line 262, in __getitem__
    pickle_kwargs=self.pickle_kwargs)
  File "/home/irhamta/anaconda3/envs/agnfit/lib/python2.7/site-packages/numpy/lib/format.py", line 696, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
```

Do you know how to solve it? Any advice you have would be appreciated! Thanks!

**Comment by LauraMR112** [comment]
Hi, 
I had the same error and I could fix it by changing line 139 of the **CONSTRUCT_modelobjects.py** file in the _functions_ folder.  In this part of the code, a pickled object is load with` np.load()` and in order to avoid the error we need to set the parameter  **allow_pickle** to **True**. So, I changed:

`npzfile = np.load(self.path + 'models/STARBURST/dalehelou_charyelbaz_files.npz')`

for

`npzfile = np.load(self.path + 'models/STARBURST/dalehelou_charyelbaz_files.npz', allow_pickle=True)`

I hope it works out for you, too.

**Comment by irhamta** [comment]
Hi Laura,

I followed your suggestion and now it works. Thank you very much for your help!
