### ISSUE TITLE
New AGNfitter-rx_v0.1: operands could not be broadcast together with shapes (10,10) (9,)

### ISSUE THREAD

**Issue by ritish142857** [GabrielaCR/AGNfitter#28]
Hi, I am using the new AGNfitterversion and I am facing this problem. I have used 9 data points and filters.  
Properties of the sampling results:
- Mean acceptance fraction 0.27182
- Mean autocorrelation time 0.8996390361395165
/home/ritish/Documents/AGNfitter/functions/PLOTandWRITE_AGNfitter.py:608: RuntimeWarning: divide by zero encountered in log10
  TOinterp = scipy.interpolate.interp1d(all_tor_nus, np.log10(tor_Fnus.flatten()),  kind = 'linear', bounds_error=False, fill_value=-100) #quadratic
Traceback (most recent call last):
  File "./RUN_AGNfitter_multi.py", line 226, in RUN_AGNfitter_onesource_independent
    PLOTandWRITE_AGNfitter.main(data, models,  P,  out, models_settings)
  File "/home/ritish/Documents/AGNfitter/functions/PLOTandWRITE_AGNfitter.py", line 58, in main
    print( '- Mean acceptance fraction', chain_mcmc.mean_accept)
AttributeError: 'CHAIN' object has no attribute 'mean_accept'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./RUN_AGNfitter_multi.py", line 386, in <module>
    RUN_AGNfitter_onesource_independent(args.sourcenumber, data_ALL, filters_settings, models_settings, clobbermodel=clobbermodel)
  File "./RUN_AGNfitter_multi.py", line 231, in RUN_AGNfitter_onesource_independent
    PLOTandWRITE_AGNfitter.main(data, models, P, out, models_settings)        
  File "/home/ritish/Documents/AGNfitter/functions/PLOTandWRITE_AGNfitter.py", line 61, in main
    output = OUTPUT(chain_mcmc, data, models, P, models_settings)
  File "/home/ritish/Documents/AGNfitter/functions/PLOTandWRITE_AGNfitter.py", line 155, in __init__
    fluxobj_4SEDplots.fluxes(self.data, self.models)
  File "/home/ritish/Documents/AGNfitter/functions/PLOTandWRITE_AGNfitter.py", line 668, in fluxes
    self.filtered_modelpoints_nuLnu = (filtered_modelpoints *lumfactor* 10**(data.nus))
ValueError: operands could not be broadcast together with shapes (10,10) (9,)

**Comment by GabrielaCR** [comment]
Hi! That seems to be the same issue as solved here: https://github.com/GabrielaCR/AGNfitter/issues/14 
I hope this helps!

**Comment by ritish142857** [comment]
Thanks, it solved the issue. but I have many queries that I want to ask from you.
